#!/bin/sh

if [ "$U_ID" != $(stat -c '%u' /app) ] || [ "$G_ID" != $(stat -c '%g' /app) ]; then
    echo "Changing /app folder permissions."

    chown $U_ID:$G_ID /app
    chown -R $U_ID:$G_ID $(ls -A /app | grep -Ev 'node_modules|.git')
fi